version: '3.9'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: .
    command: >
      sh -c "python wait_for_postgres.py && uvicorn src.audioscribetranslate.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  celery:
    build: .
    command: python src/audioscribetranslate/worker_manager.py
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - /var/run/docker.sock:/var/run/docker.sock # Для управления Docker контейнерами
    env_file:
      - .env
    depends_on:
      - db
      - redis
    privileged: true # Необходимо для мониторинга системных ресурсов

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
