"""add whisper_model to audio_file

Revision ID: 176deed87d24
Revises: b4833ee574d4
Create Date: 2025-08-08 14:43:01.028905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176deed87d24'
down_revision: Union[str, Sequence[str], None] = 'b4833ee574d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_files', sa.Column('whisper_model', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_files', 'whisper_model')
    # ### end Alembic commands ###
